### PR TITLE
ci: replace travis with github actions

### PR DESCRIPTION
**Pull request by inigomarquinez**
This PR migrates the CI from travis to GitHub actions (agreed to migrate to GH actions [here](https://github.com/expressjs/discussions/issues/229))

@UlisesGascon, the project would need to be removed from [travis](https://app.travis-ci.com/github/expressjs/morgan)

The new ci action and README.md changes are based on the respective files in [cookie](https://github.com/jshttp/cookie) repository

Action passing at [my fork](https://github.com/inigomarquinez/expressjs-morgan/actions/runs/9004991169)

### CODE REVIEW

**Review by UlisesGascon — APPROVED** [review]
LGTM!

**Comment by UlisesGascon** [comment]
The new pipeline works as expected, [see](https://github.com/expressjs/morgan/actions/runs/9083011155) for more details.

**Comment by UlisesGascon** [comment]
I was not able to remove the project from Travis, maybe @wesleytodd can do the magic? https://app.travis-ci.com/github/expressjs/morgan

**Comment by wesleytodd** [comment]
I do have access to the administrative parts, but I am not sure what to do. I have not really used travis in so long I don't think I have ever seen this UI for managing things. I checked "off" the "build branches" and "build prs". Is that enough?

**Pull request merged**
