### PR TITLE
Record response time at response end instead of response start

### PR DESCRIPTION
**Pull request by bobwei**
Should record response time at response end instead of response start so that we can record whole response time for streaming response.

### CODE REVIEW

**Comment by dougwilson** [comment]
Also the docs need to be updated (though since this should be a new option,  add new docs). Here is the current docs:

> :response-time[digits]
> The time between the request coming into morgan and when the response headers are written, in milliseconds.

**Comment by dougwilson** [comment]
Hi @bobwei sorry I never came back to this PR. I just realized that instead of landing this as a flag that changes the behavior of an existing token, we should modify the PR to just add a new token with the behavior, which same the same ultimate outcome, but the benefit of being able to include both of these times in the output if that's desired.

**Comment by dougwilson** [comment]
I have just written all the code to move this to a `:total-time` token. If you are agreeable on this approach, I can squash this into your PR here and merge as your PR still.

**Comment by bobwei** [comment]
Hi @dougwilson, sure, please proceed.

**Comment by pjsg** [comment]
Can this be merged please?

**Comment by bobwei** [comment]
Go go

**Pull request closed without merging**
