### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Allanbikundo**
Hello there

So rotating-file-stream now needs one to call the function createStream to work

### CODE REVIEW

**Comment by jonchurch** [comment]
Closes #217

**Comment by a10kiloham** [comment]
+1 - please push this README change; it just happened to me and had to google to get here :)

**Comment by dougwilson** [comment]
I'm just waiting for the requested change to be made from the review comment. If I don't hear back in a week or so I will make the change myself instead, but then OP will loose credit on it, so wanted to give a chance.

**Comment by ryhinchey** [comment]
@Allanbikundo  thank for this PR!  There's a request [here](https://github.com/expressjs/morgan/pull/218#pullrequestreview-343393630) to update the docs to reference the version of `rfs` that doesn't have a default export. Here's the `rfs` v1 > v2 upgrade docs: https://github.com/iccicci/rotating-file-stream#upgrading-from-v1xx-to-v2xx

Is this a change you can make? That seems to be the only thing left to get this PR in.

**Pull request closed without merging**
