### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by PeterDaveHello**
also test on node.js v4.0/4.1

### CODE REVIEW

**Comment by dougwilson** [comment]
Hi! We don't typically take updates to the Travis CI configuration file unless it fixes a bug or there's more of a reason to test vs. just "well, it's the latest". I haave gone ahead and accepted this PR anyway :)

**Comment by PeterDaveHello** [comment]
But why not test on v4.x? I think 4.2 should be added as it's a LTS version!

**Comment by dougwilson** [comment]
Your PR only had 4.1.

**Comment by PeterDaveHello** [comment]
What about reopen and let me change to v4.2 :smile: v4.2 was not out when I sending this PR.

**Pull request closed without merging**
