### PR TITLE
docs: Fix doc due to return undefined

### PR DESCRIPTION
**Pull request by koooge**
Hello. This PR just fix doc. morgan returns status = undefined, not '-'.
https://github.com/expressjs/morgan/blob/master/index.js#L266

### CODE REVIEW

**Comment by dougwilson** [comment]
All falsy values are displayed as `-` in the logs.

**Comment by gms-ta-koge** [comment]
Hmm, in my env with express

```
app.use(morgan(function (tokens, req, res) {
  return [
    tokens.method(req, res),
    tokens.url(req, res),
    tokens.status(req, res),
    tokens.res(req, res, 'content-length'), '-',
    tokens['response-time'](req, res), 'ms'
  ].join(' ')
}));

app.use('/foo', (req, res) => {
  // nop
});
```

outputs
`GET /foo   -  ms`

tokens.status is not '-', right?

**Comment by koooge** [comment]
Hmm, in my env with express

```
app.use(morgan(function (tokens, req, res) {
  return [
    tokens.method(req, res),
    tokens.url(req, res),
    tokens.status(req, res),
    tokens.res(req, res, 'content-length'), '-',
    tokens['response-time'](req, res), 'ms'
  ].join(' ')
}));

app.use('/foo', (req, res) => {
  // nop
});
```

outputs
`GET /foo - ms`

tokens.status is not '-', right?

**Comment by dougwilson** [comment]
The note you removed is

> displayed as `"-"` in the log

That is not documenting the actual return value of the function.

**Comment by dougwilson** [comment]
If you provide a custom function it will display however you make the string. Try this instead:
```
app.use(morgan(':method :url :status :res[content-length] :response-time ms'));

app.use('/foo', (req, res) => {
  // nop
});
```

**Comment by koooge** [comment]
Thank you for your quick response. I will try it 🙇

**Pull request closed without merging**
